services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - php
    networks:
      - php_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  php:
    container_name: php
    depends_on:
      - mysql
    build:
      dockerfile: ./php/Dockerfile
    networks:
      - php_network
    env_file:
      - .env
    volumes:
      - ./app:/var/www/html
      - ./app/tests:/var/www/html/tests
      - ./app/phpunit.xml:/var/www/html/phpunit.xml
    extra_hosts:
      - host.docker.internal:host-gateway
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - php_network
networks:
  php_network:
    name: php_network
    ipam:
      config:
        - subnet: 172.28.0.0/16
volumes:
  mysqldata: